[package]
name = "aster"
version = "0.9.3"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A libsyntax ast builder"
repository = "https://github.com/serde-rs/aster"

[features]
with-syntex = ["syntex_syntax"]
unstable = ["clippy", "compiletest_rs"]

[dependencies]
syntex_syntax = { version = "^0.25.0", optional = true, path = "../syntex/syntex_syntax/" }
clippy = { version = "^0.0.33", optional = true }
compiletest_rs = { version = "^0.0.11", optional = true }

[[test]]
name = "test"
path = "tests/test.rs"
